# fly.toml app configuration file generated for stocksapp-clean on 2023-08-22T10:23:36+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "stocksapp-clean"
primary_region = "arn"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
